var searchData=
[
  ['templmatchingdetector',['TemplMatchingDetector',['../class_viscv_1_1_templ_matching_detector.html',1,'Viscv']]],
  ['templmatchingtracker',['TemplMatchingTracker',['../class_viscv_1_1_templ_matching_tracker.html',1,'Viscv']]],
  ['tracker',['Tracker',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20circle_3c_3e_20_3e',['Tracker&lt; cv::Mat, Circle&lt;&gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20cv_3a_3arect_20_3e',['Tracker&lt; cv::Mat, cv::Rect &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20std_3a_3amap_3c_20long_2c_20biometrics_3a_3aperson_20_3e_20_3e',['Tracker&lt; cv::Mat, std::map&lt; long, Biometrics::Person &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20std_3a_3amap_3c_20long_2c_20cv_3a_3arect_20_3e_20_3e',['Tracker&lt; cv::Mat, std::map&lt; long, cv::Rect &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20std_3a_3avector_3c_20cv_3a_3apoint2f_20_3e_20_3e',['Tracker&lt; cv::Mat, std::vector&lt; cv::Point2f &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20cv_3a_3amat_2c_20std_3a_3avector_3c_20std_3a_3avector_3c_20cv_3a_3apoint_20_3e_20_3e_20_3e',['Tracker&lt; cv::Mat, std::vector&lt; std::vector&lt; cv::Point &gt; &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20timg_2c_20std_3a_3amap_3c_20long_2c_20tobj_20_3e_20_3e',['Tracker&lt; TImg, std::map&lt; long, TObj &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['tracker_3c_20timg_2c_20std_3a_3avector_3c_20tobj_20_3e_20_3e',['Tracker&lt; TImg, std::vector&lt; TObj &gt; &gt;',['../class_vision_core_1_1_interfaces_1_1_tracker.html',1,'VisionCore::Interfaces']]],
  ['trackercontrol',['TrackerControl',['../class_tracker_control.html',1,'']]],
  ['trackercontrol_3c_20cv_3a_3amat_2c_20cv_3a_3arect_20_3e',['TrackerControl&lt; cv::Mat, cv::Rect &gt;',['../class_tracker_control.html',1,'']]],
  ['trackercontrol_3c_20cv_3a_3amat_2c_20std_3a_3amap_3c_20long_2c_20biometrics_3a_3aperson_20_3e_20_3e',['TrackerControl&lt; cv::Mat, std::map&lt; long, Biometrics::Person &gt; &gt;',['../class_tracker_control.html',1,'']]],
  ['trackercontrol_3c_20cv_3a_3amat_2c_20std_3a_3avector_3c_20cv_3a_3apoint2f_20_3e_20_3e',['TrackerControl&lt; cv::Mat, std::vector&lt; cv::Point2f &gt; &gt;',['../class_tracker_control.html',1,'']]],
  ['trackerevaluator',['TrackerEvaluator',['../class_vision_core_1_1_evaluation_1_1_tracker_evaluator.html',1,'VisionCore::Evaluation']]],
  ['trackerlogger',['TrackerLogger',['../class_vision_core_1_1_abstractions_1_1_tracker_logger.html',1,'VisionCore::Abstractions']]],
  ['trackerlogger_3c_20cv_3a_3amat_2c_20cv_3a_3arect_20_3e',['TrackerLogger&lt; cv::Mat, cv::Rect &gt;',['../class_vision_core_1_1_abstractions_1_1_tracker_logger.html',1,'VisionCore::Abstractions']]],
  ['trackerlogger_3c_20cv_3a_3amat_2c_20std_3a_3amap_3c_20long_2c_20biometrics_3a_3aperson_20_3e_20_3e',['TrackerLogger&lt; cv::Mat, std::map&lt; long, Biometrics::Person &gt; &gt;',['../class_vision_core_1_1_abstractions_1_1_tracker_logger.html',1,'VisionCore::Abstractions']]],
  ['trackerlogger_3c_20cv_3a_3amat_2c_20std_3a_3avector_3c_20cv_3a_3apoint2f_20_3e_20_3e',['TrackerLogger&lt; cv::Mat, std::vector&lt; cv::Point2f &gt; &gt;',['../class_vision_core_1_1_abstractions_1_1_tracker_logger.html',1,'VisionCore::Abstractions']]],
  ['trackingdata',['TrackingData',['../struct_vision_core_1_1_abstractions_1_1_tracking_data.html',1,'VisionCore::Abstractions']]],
  ['trackingdata_3c_20cv_3a_3arect_20_3e',['TrackingData&lt; cv::Rect &gt;',['../struct_vision_core_1_1_abstractions_1_1_tracking_data.html',1,'VisionCore::Abstractions']]],
  ['trackingdata_3c_20std_3a_3amap_3c_20long_2c_20biometrics_3a_3aperson_20_3e_20_3e',['TrackingData&lt; std::map&lt; long, Biometrics::Person &gt; &gt;',['../struct_vision_core_1_1_abstractions_1_1_tracking_data.html',1,'VisionCore::Abstractions']]],
  ['trackingdata_3c_20std_3a_3avector_3c_20cv_3a_3apoint2f_20_3e_20_3e',['TrackingData&lt; std::vector&lt; cv::Point2f &gt; &gt;',['../struct_vision_core_1_1_abstractions_1_1_tracking_data.html',1,'VisionCore::Abstractions']]],
  ['trackingdataset',['TrackingDataset',['../class_vision_core_1_1_evaluation_1_1_tracking_dataset.html',1,'VisionCore::Evaluation']]],
  ['trackingdataset_3c_20cv_3a_3amat_2c_20tobj_20_3e',['TrackingDataset&lt; cv::Mat, TObj &gt;',['../class_vision_core_1_1_evaluation_1_1_tracking_dataset.html',1,'VisionCore::Evaluation']]],
  ['trackingdatasetcontrol',['TrackingDatasetControl',['../class_tracking_dataset_control.html',1,'']]],
  ['trackingdatasetwidget',['TrackingDatasetWidget',['../class_tracking_dataset_widget.html',1,'']]],
  ['trackingevalresult',['TrackingEvalResult',['../struct_vision_core_1_1_evaluation_1_1_tracking_eval_result.html',1,'VisionCore::Evaluation']]]
];
