var annotated_dup =
[
    [ "Ui", null, [
      [ "DetectorControlWidget", "class_ui_1_1_detector_control_widget.html", null ],
      [ "FrameServerControlWidget", "class_ui_1_1_frame_server_control_widget.html", null ],
      [ "ImageViewerCv", "class_ui_1_1_image_viewer_cv.html", null ],
      [ "ProcessWidget", "class_ui_1_1_process_widget.html", null ]
    ] ],
    [ "Viscv", "namespace_viscv.html", "namespace_viscv" ],
    [ "VisionCore", "namespace_vision_core.html", "namespace_vision_core" ],
    [ "DatasetFire", "class_dataset_fire.html", "class_dataset_fire" ],
    [ "DetectionDatasetControl", "class_detection_dataset_control.html", "class_detection_dataset_control" ],
    [ "DetectorControl", "class_detector_control.html", "class_detector_control" ],
    [ "DetectorControlWidget", "class_detector_control_widget.html", "class_detector_control_widget" ],
    [ "FaceDetectorControl", "class_face_detector_control.html", "class_face_detector_control" ],
    [ "FaceRecogTrackerControl", "class_face_recog_tracker_control.html", "class_face_recog_tracker_control" ],
    [ "FeatureTrackerControl", "class_feature_tracker_control.html", "class_feature_tracker_control" ],
    [ "FireTrackerChenebert", "class_fire_tracker_chenebert.html", "class_fire_tracker_chenebert" ],
    [ "FireTrackerCT", "class_fire_tracker_c_t.html", "class_fire_tracker_c_t" ],
    [ "FireTrackerSA", "class_fire_tracker_s_a.html", "class_fire_tracker_s_a" ],
    [ "FrameServerControlWidget", "class_frame_server_control_widget.html", "class_frame_server_control_widget" ],
    [ "ImageViewerCv", "class_image_viewer_cv.html", "class_image_viewer_cv" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "ObjectTrackerPFHistControl", "class_object_tracker_p_f_hist_control.html", "class_object_tracker_p_f_hist_control" ],
    [ "ObjectTrackerStruck", "class_object_tracker_struck.html", "class_object_tracker_struck" ],
    [ "ProcessControl", "class_process_control.html", "class_process_control" ],
    [ "ProcessWidget", "class_process_widget.html", "class_process_widget" ],
    [ "qt_meta_stringdata_DetectorControlWidget_t", "structqt__meta__stringdata___detector_control_widget__t.html", "structqt__meta__stringdata___detector_control_widget__t" ],
    [ "qt_meta_stringdata_FrameServerControlWidget_t", "structqt__meta__stringdata___frame_server_control_widget__t.html", "structqt__meta__stringdata___frame_server_control_widget__t" ],
    [ "qt_meta_stringdata_ImageViewerCv_t", "structqt__meta__stringdata___image_viewer_cv__t.html", "structqt__meta__stringdata___image_viewer_cv__t" ],
    [ "qt_meta_stringdata_ProcessWidget_t", "structqt__meta__stringdata___process_widget__t.html", "structqt__meta__stringdata___process_widget__t" ],
    [ "TrackerControl", "class_tracker_control.html", "class_tracker_control" ],
    [ "TrackingDatasetControl", "class_tracking_dataset_control.html", "class_tracking_dataset_control" ],
    [ "TrackingDatasetWidget", "class_tracking_dataset_widget.html", "class_tracking_dataset_widget" ],
    [ "Ui_DetectorControlWidget", "class_ui___detector_control_widget.html", "class_ui___detector_control_widget" ],
    [ "Ui_FrameServerControlWidget", "class_ui___frame_server_control_widget.html", "class_ui___frame_server_control_widget" ],
    [ "Ui_ImageViewerCv", "class_ui___image_viewer_cv.html", "class_ui___image_viewer_cv" ],
    [ "Ui_ProcessWidget", "class_ui___process_widget.html", "class_ui___process_widget" ],
    [ "VisionWidgets", "class_vision_widgets.html", "class_vision_widgets" ]
];